# Generated by Django 4.0.2 on 2023-02-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('provider', models.CharField(max_length=50)),
                ('issued', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
                ('subject', models.CharField(blank=True, default='', max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=50)),
                ('board', models.CharField(blank=True, default='', max_length=50)),
                ('result', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=250)),
                ('post', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=120)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
            ],
            options={
                'verbose_name': 'Extra',
                'verbose_name_plural': 'Extras',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='pics')),
                ('email', models.EmailField(max_length=254)),
                ('tagline', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='vids')),
                ('href', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField()),
                ('tools', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('Proficient', 'Proficient'), ('Familiar', 'Familiar')], max_length=50)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Project_urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('background', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aldrinsaurovsarker.projects')),
            ],
            options={
                'verbose_name': 'Project url',
                'verbose_name_plural': 'Project urls',
            },
        ),
    ]
