# Generated by Django 4.0.2 on 2023-03-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldrinsaurovsarker', '0002_alter_projects_ptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='level',
            field=models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Web Technology', 'Web Technology'), ('Database', 'Database')], max_length=50),
        ),
    ]
